### ISSUE TITLE
Suggestion: save state in query string

### ISSUE THREAD

**Issue by layday** [ogri-la/wowman-comrades#1]
This would make it possible to e.g. link to Linux-compatible CLIs only.

**Comment by torkus** [comment]
This is a sound idea.

I plan on doing some basic platform sniffing to pre-select a linux/mac/windows profile as well. It would make sense to skip that if explicit parameters had been passed in

**Comment by torkus** [comment]
work happening here: https://github.com/ogri-la/wowman-comrades/pull/2

**Comment by torkus** [comment]
my [perfect addon manager](https://ogri-la.github.io/wow-addon-managers/?field/maintained=yes&field/windows=yes&field/eula=no&field/ads=no&field/ui=GUI&field/retail=yes&field/linux=yes&field/f-oss=yes&field/classic=yes&field/mac=yes) doesn't exist :(

... but I bought a mac mini and resurrected an old windows machine so some proper support won't be too far away now. wowman works surprisingly well on a 2007 Windows Vista machine. Some problems with paths inside zip files but I think I know what is going on.

**Comment by layday** [comment]
On the Mac you can push the menu bar over to the system menu bar with `native!` in seesaw (first thing I did after forking wowman ;P).

**Comment by torkus** [comment]
I'm not a mac/windows user at all - they really infuriate me every step of the way actually - so beyond simply having it work on those platforms I'm going to rely on others for feedback on proper platform idioms like you just described. Feel free to open pull requests with your changes, I just won't be able to properly test and merge them until I have a mac setup running.

**Comment by torkus** [comment]
oh - and are you satisfied with the url parameter support? did I close the ticket too early?

**Comment by layday** [comment]
Well, I thought the query could've been updated on the fly rather than having to click on 'permalink', and then you could also go back to 'undo' state changes.

**Comment by torkus** [comment]
> then you could also go back to 'undo' state changes.

do you like using the 'back' button? 

My web knowledge is pretty old school, I starting hating html/css/the web/humanity about the time HTML5 and social media came around, but it looks like you can futz with the address URL without causing a refresh these days. I'll add a TODO to take a look later.

**Comment by layday** [comment]
Being able to futz with the address seems rather benign in the grand scheme of single-page apps -  you aren't running a cryptominer in the background, are you?  The worst part is how all of this crap's found its way into other media, including the command line: the de facto OS X package manager [uses Google Analytics](https://docs.brew.sh/Analytics).  I can't wait for the day I'll be able to `brew like` a package straight from my terminal.

**Comment by torkus** [comment]
> you aren't running a cryptominer in the background, are you?

I get the humour, but [the first lines in the wowman README](https://github.com/ogri-la/wowman/blob/develop/README.md) are true of all my projects even if I haven't stated it explicitly for this particular project. The right to privacy is considered a fundamental and inalienable human right, despite the behaviour and policies of our governments. We have expectations about how software should behave and just because we *can* subvert those expectations and do some shady shit in the background like track who what when and where (or use their machine's resources to do something other than the declared purpose of the program) doesn't mean we should. Basic ethics.

>  the de facto OS X package manager uses Google Analytics

Just awful. I remember how betrayed I felt when Ubuntu started sending keystrokes from their desktop search field to third party affiliates like Amazon and Google and eBay etc. On by default. It really was the beginning of the slippery slope. Their server distribution is a little better but I still find myself having to disable a bunch of unnecessary crap they include and enable by default. I don't touch it outside of work though.

**Comment by torkus** [comment]
> do you like using the 'back' button?

heh - what I meant here was: "do you **mean** like using the 'back' button?". I think I know what you're saying. Clicking back to 'undo' a change to a filter and copying from the address bar are much more natural than the permalink widget I have going on.

**Comment by layday** [comment]
You inspired me to add [this](https://github.com/layday/instawow#remote-hosts) section to my readme.

**Comment by torkus** [comment]
Very cool, I'm pleased my small efforts are affecting others.

This seems to be a good time to tell you I'm stealing your "reconcile" and renaming my "re-install all" feature to it.

**Comment by layday** [comment]
haha, feel free.

**Comment by layday** [comment]
I stole your idea of having it being done [automatically](https://github.com/layday/instawow/commit/2c31691426c661eabca50ab13dce97a05a04599b) as payback ;)

**Comment by torkus** [comment]
You've just revealed you've been reading my TODO file ;)

Automatic reconciliation seems sensible and easy enough to implement. Let me know if you encounter any problems though.

On a related note, how does Instawow update addons? I'm thinking of deleting and then unzipping rather than just unzipping and overwriting. It would solve a couple of weird cases but may be unexpectedly destructive for users.

**Comment by layday** [comment]
Guilty as charged.

> Automatic reconciliation seems sensible and easy enough to implement. Let me know if you encounter any problems though.

WoWI tends to lag behind/is neglected by add-on authors so my biggest 'problem' is having to default to installing from Curse.

> On a related note, how does Instawow update addons?

It uninstalls the installed version then installs the new version however it doesn't actually delete anything; it moves the old version's folders under `$TMPDIR/instawow` and lets the OS delete them either periodically (e.g. some Linuxes) or on the next boot (Macs).  This is supposed to act as some kind of safety net (e.g. if instawow isn't able to complete the update or if the new version is giving you a headache or if you made local changes to the add-on you'd want to copy over to the new version) but it's too obscure to be of any actual use to anybody other than me.  I toyed with the idea of adding a `rollback` command to restore deleted add-ons at one point.

**Comment by torkus** [comment]
> WoWI tends to lag behind/is neglected by add-on authors so my biggest 'problem' is having to default to installing from Curse.

ha, I just do it alphabetically if there are multiple matches from different sources, and **C**urseforge just happens to come first well, there's nothing I can do people, it's just physics. 

> It uninstalls the installed version then installs the new version however it doesn't actually delete anything; it moves the old version's folders under $TMPDIR/instawow and lets the OS delete them either periodically (e.g. some Linuxes) or on the next boot (Macs). 

which linuxes empty the temp directory periodically? That could actually be quite dangerous ... years and years and years ago 'they' used to recommend a separate partition for /tmp but these days it's typically a tmpfs volume that gets unmounted on shutdown, destroying whatever it stored.

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
...
tmpfs            16G   36M   16G   1% /tmp
```

**Comment by layday** [comment]
RHEL:

> As you’ll find on the timer unit, it will run just 15 minutes after systemd start, and then every 24 hours from that time onward. The command, in this case, will only affect files/directories purging/cleaning.

https://developers.redhat.com/blog/2016/09/20/managing-temporary-files-with-systemd-tmpfiles-on-rhel7/

[Some others?](https://serverfault.com/questions/377348/when-does-tmp-get-cleared)
