### ISSUE TITLE
Consider collapsing feature 'wowace' into 'curseforge'

### ISSUE THREAD

**Issue by layday** [ogri-la/wowman-comrades#10]
WowAce uses the same backend as CurseForge.  instawow and I think CurseBreaker (though I haven't checked to confirm) will happily [match](https://github.com/layday/instawow/blob/0fae096/instawow/resolvers.py#L130-L132) WowAce URLs against the CurseForge API.  WowAce used to be separate and it might be better to think of old WowAce as a separate entity - there are abandoned add-on managers in the catalogue with the 'wowace' feature that used to be able to scrape the original WowAce and managers which are actively maintained which scrape the new but old but new WowAce website but not in exclusion of CurseForge.

**Comment by torkus** [comment]
I haven't looked into it too deeply, just saw the feature keep coming up. I had the impression WowAce was an addon-developer type community that naturally preferred the bleeding edge of things. So does everything from Curseforge now include Wowace content as well?

**Comment by layday** [comment]
I don't think there's much of a developer community left on WowAce though it did use to be that.  Yes, WowAce add-ons are sourced from the same database.

**Comment by torkus** [comment]
I think I'll remove the WowAce feature column. I'm not sure what it is anymore but as far as I can tell wowace is dead.

**Comment by torkus** [comment]
WowAce column removed. The values weren't merged into the Curseforge column as the two were distinct once and this is what the spreadsheet was capturing.
