### ISSUE TITLE
cursebreaker may support vcs addons

### ISSUE THREAD

**Issue by torkus** [ogri-la/wowman-comrades#13]

**Comment by AcidWeb** [comment]
Not directly. It support pulling packages from GitHub releases and packaged snapshots from TukUI GitLab but it don't use git directly.

**Comment by torkus** [comment]
strongbox does something similar. I'll make sure there is the caveat asterisk * next to it.

**Comment by torkus** [comment]
[done](https://ogri-la.github.io/wow-addon-managers/?preset/name=unfiltered&field/feature-curseforge=&field/maintained=&field/windows=&field/eula=&field/feature-tukui=&field/ads=&field/source-available=&field/feature-wowinterface=&field/ui=&field/language=&field/feature-vcs-addons=yes^&field/retail=&field/linux=&field/feature-wowace=&field/f-oss=&field/classic=&field/mac=&field/feature-catalog-search=)
