### ISSUE TITLE
Please add implementation language and license to the table.

### ISSUE THREAD

**Issue by egorpugin** [ogri-la/wowman-comrades#18]

**Comment by torkus** [comment]
I'm sorry if it wasn't clear, but you can see the complete unfiltered list of data by selecting 'unfiltered' in the top left drop down.

I don't capture the licence itself but I do capture whether the project is free/open source software (the F/OSS column) and make a distinction between 'free/open source' and 'source available'.

If you are after the exact licence being used may I know your usecase?

**Comment by egorpugin** [comment]
> I'm sorry if it wasn't clear, but you can see the complete unfiltered list of data by selecting 'unfiltered' in the top left drop down.

Oh. I see.
There's language and foss flag in unfiltered mode.
Is it possible to add lang column to default mode? Maybe on the right side after features.

> I don't capture the licence itself but I do capture whether the project is free/open source software (the F/OSS column) and make a distinction between 'free/open source' and 'source available'.

FOSS column is a bit unclear. It is possible to merge foss/eula flag into one column 'license'.
Within 'license' you say whether it MIT/BSD/GPL or Proprietary/EULA.
(You could use SPDX identifiers for this https://spdx.org/licenses/)

> If you are after the exact licence being used may I know your usecase?

Some people choose software by license (and probably PL also). :)

**Comment by torkus** [comment]
> Is it possible to add lang column to default mode? 

The 'default' view of the list is aimed at the broadest audience while trying to be inclusive of those gaming on other operating systems. It also tries to limit 'data overload' and prevent glazed eyeballs. 

The default view is not targeted at software developers or privacy advocates unfortunately. 

> FOSS column is a bit unclear. It is possible to merge foss/eula flag into one column 'license'.

An EULA [is distinct from a software licence](https://en.wikipedia.org/wiki/End-user_license_agreement).

> Within 'license' you say whether it MIT/BSD/GPL or Proprietary/EULA.
(You could use SPDX identifiers for this https://spdx.org/licenses/)

I can add a licence field. The value displayed will be the one pulled from Github (as almost all of these managers are hosted there).

**Comment by torkus** [comment]
Licence field has been added: https://ogri-la.github.io/wow-addon-managers/?preset/name=unfiltered

For software without a licence (or is proprietary software) I've used the SPDX "noassertion" identifier - it was more appropriate than leaving it blank, or using 'none' or 'no' etc.

The field is available on the unfiltered view and the linux views.

**Comment by egorpugin** [comment]
Thank you!

**Comment by torkus** [comment]
my pleasure, thank you for opening a ticket
