### ISSUE TITLE
Another one for the list

### ISSUE THREAD

**Issue by layday** [ogri-la/wowman-comrades#21]
This was on reddit today: https://singularitymods.com/

**Comment by torkus** [comment]
cheers, @layday . Did everybody get super excited? It looks properly dodgy to me.

**Comment by torkus** [comment]
it's being served out of a bucket fronted by a poorly configured CDN:

```
$ curl -I -l https://singularitymods.com
HTTP/2 200 
content-type: text/html
content-length: 3152
date: Tue, 29 Sep 2020 13:25:14 GMT
last-modified: Mon, 28 Sep 2020 14:07:29 GMT
etag: "5d3cddc756b781034451e987f0ea5251"
accept-ranges: bytes
server: AmazonS3
x-cache: Miss from cloudfront
via: 1.1 19d11cb6f474bd40cf37b78c591bf419.cloudfront.net (CloudFront)
x-amz-cf-pop: PHX50-C2
x-amz-cf-id: KmSB4xbSqEv1Z7daKgVOzaL_mrWgrn9WrV39JRNmohhwV3truWrGOQ==

$ curl -I -l https://singularitymods.com
HTTP/2 200 
content-type: text/html
content-length: 3152
date: Tue, 29 Sep 2020 13:25:45 GMT
last-modified: Mon, 28 Sep 2020 14:07:29 GMT
etag: "5d3cddc756b781034451e987f0ea5251"
accept-ranges: bytes
server: AmazonS3
x-cache: Miss from cloudfront
via: 1.1 e060b509c62f974a7b10f99332ebb272.cloudfront.net (CloudFront)
x-amz-cf-pop: PHX50-C2
x-amz-cf-id: nHNmtaqiAOmR9rllOnqNhtPRuUYzFxnEnx7Fm6kVl1RkuDq8yRE1HQ==
```

any real traffic would cost them a fortune :(

**Comment by layday** [comment]
It appears to have been well received though not to the extent of WowUp or Ajour (which was featured on Wowhead today). The author said they plan to open source it after they 'iron out the bugs and clean up any spaghetti code'.

**Comment by torkus** [comment]
They started a subreddit and a discord channel and a weird 'freshdesk' issue tracker - I don't get an open source vibe from them.

**Comment by torkus** [comment]
while I'm here, some more that need triage:

* https://github.com/TiredCoders/wow-pantheon
* https://github.com/ccarlfjord/wow-addon-manager
* ~https://github.com/gravenuance/WoWoh~
  - looks like this one has been deleted. 
  * Apropos of *nothing*, gravenuance is a [good lookin' man](https://github.com/gravenuance). Just saying.
* https://github.com/Birkbjo/underdog
* https://github.com/soofm/Malediction
* https://github.com/joheri85/SmoskAddonManager
* https://github.com/bitobrian/addonager

**Comment by layday** [comment]
No, I don't either.  I mean, they've even registered a company under the name "Singularity LLC".

**Comment by torkus** [comment]
I saw that while browsing their privacy policy and T&C's ... enthusiastic or naive or both? [I've seen plenty of that before](https://ogri-la.github.io/wow-addon-managers/?preset/name=unfiltered&field/feature-curseforge=&field/maintained=no&field/software-licence=&field/eula=&field/feature-tukui=&field/ads=&field/source-available=&field/feature-wowinterface=&field/ui=&field/language=&field/feature-vcs-addons=&field/retail=&field/linux=&field/f-oss=&field/classic=&field/mac=&field/feature-catalog-search=).

**Comment by layday** [comment]
Wow, that's a lot of new managers.  I guess the CF takeover by Overwolf has had an effect.

**Comment by torkus** [comment]
I'm wondering if I should re-sub before the new expansion releases. This is the longest I've been clean.

**Comment by layday** [comment]
Ajour now has a catalogue so I'm about to get company in the 'perfect' corner.

**Comment by layday** [comment]
I would of course be lying if I said I wasn't even slightly resentful that something I've been working on for 3 years was completely overshadowed in the span of a month.

**Comment by torkus** [comment]
Same. He has no tests though and has borrowed bits from other projects. [Does this look familiar?](https://github.com/casperstorm/ajour/blob/master/crates/core/src/murmur2.rs). It's also a bit of a novelty for a Rust program to have a GUI. I seriously considered the language when I started my own manager but there just wasn't anything there yet.

Still, it's 'comrades' rather than 'competition' ;)

**Comment by layday** [comment]
Ah, but they removed WoWI support in [this](https://github.com/casperstorm/ajour/commit/fd3982e612fe11d183234b18ae5f63abfb937419) commit.  My reign is not over ye....*ahem*, I mean, yes, we're all comrades.  It actually looks like they tried to use the WoWI authoring API.  There's also a few tests interspersed with the code - I think that's how they do it in Rust.

**Comment by torkus** [comment]
> Ah, but they removed WoWI support in this commit.

thanks for that. I'll update the list this weekend.

**Comment by layday** [comment]
This happened: https://www.wowhead.com/news=318455/overwolf-blog-post-on-scraping-curseforge.

**Comment by torkus** [comment]
ha - called it. We'll see what shakes out. I'm a little disappointed I haven't been contacted by Overwolf people, but I suspect it's because I don't target Windows.

Their statement is aggressive fluff and the commenters rightly tear it apart.

**Comment by torkus** [comment]
are you seeing slow-downs (throttling?) in instawow from curseforge?

update: I see the first three or so requests happen quickly then the rest slow down to a crawl

**Comment by layday** [comment]
It's pre-patch in NA - Curse, Tukui and Wago are all suffering.

**Comment by torkus** [comment]
ah interesting. I'll ignore the odd behaviour for now then.

**Comment by layday** [comment]
Overwolf invited the authors of Ajour and WowUp to a video call - they were told they'd not be revisiting the API until Q1 or Q2 2021 and that it's still operated by Twitch.

**Comment by torkus** [comment]
pfft - they're nobodies. Still in nappies. I want a video call! waaaaahhh.

jk. It's the very last thing I want. My skin crawls at the very idea. I'm quite happy offering up these newcomers to this new greedy and litigious god.

I think wowinterface.com should step up or a means of releasing on github and then aggregating and curating the results put in place though. Convenience often trumps principals though.

**Comment by layday** [comment]
I'd like to see a freely-licensed catalogue of add-ons available from GitHub.  But add-on devs appear to be overwhelmingly opposed to the idea of anything of the sort 'cause of the whole WowMatrix fiasco which had some of them misguidedly abandon FOSS licences to 'prevent' redistribution.  Then there's the Curse rewards programme which effectively locks them into the platform.  Aren't corporations just wonderful.

**Comment by layday** [comment]
instawow was mentioned in [this](https://www.wowhead.com/guides/best-addon-managers-wow-shadowlands) article.  They wrongly claim that it does not support PTR and beta and that it overwrites add-ons... I wonder if the aim was to drive users away.

**Comment by torkus** [comment]
Did you write to them and ask for a correction? Those sort of articles on wowhead kick around for years and years so you want them to be accurate.

But hey - no such thing as bad press.

**Comment by layday** [comment]
I have, they made some corrections but it still says 'can accidentally overwrite Retail with Classic versions and vice/versa'.  The reviewer attempted to change the flavour (or track in strongbox parlance) from the dropdown expecting that instawow would automagically switch to managing their classic folder.

**Comment by torkus** [comment]
eh, they're Windows users. They don't have package managers and everybody has a virus scanner. I bet their printers Just Work as well.

**Comment by layday** [comment]
Ajour has added proper support for WoWI and WowUp is now available for Mac and Linux.
