### ISSUE TITLE
ClassicAddonManager supports retail and Tukui

### ISSUE THREAD

**Issue by erikabp123** [ogri-la/wowman-comrades#23]
[ClassicAddonmanager](https://github.com/erikabp123/ClassicAddonManager) supports retail as well as retail ptr and classic ptr now. It also supports Tukui and has for at least 10+ months. As for catalog search, I'm not sure what the requirements are for that but you can search wowinterface, tukui, and curseforge directly through the manager

**Comment by torkus** [comment]
Done, thank you for opening a ticket.

> It also supports Tukui and has for at least 10+ months.

Criticism noted. Addons that are hosted on github have basic data updated regularly but thorough reviews of each addon manager and their features happens much less regularly. I've come to rely on addon manager authors to notify me of their changes.
