### ISSUE TITLE
Add support for Wago.IO support

### ISSUE THREAD

**Issue by lifebound** [ogri-la/wowman-comrades#28]
I know Cursebreaker can update weakauras, but its not a feature that can be filtered by.

**Comment by torkus** [comment]
sure, I can do that

**Comment by torkus** [comment]
Done. [You only have two choices](https://ogri-la.github.io/wow-addon-managers/?preset/name=unfiltered&field/feature-wago.io=yes&field/feature-curseforge=&field/maintained=&field/software-licence=&field/windows=&field/eula=&field/feature-tukui=&field/ads=&field/source-available=&field/feature-wowinterface=&field/ui=&field/language=&field/feature-vcs-addons=&field/retail=&field/linux=&field/f-oss=&field/classic=&field/mac=&field/feature-catalog-search=), though :(

You can find it as the last column under 'unfiltered'.

Thank you for opening a ticket.

**Comment by layday** [comment]
Ajour has this as well now.

**Comment by torkus** [comment]
list updated, cheers @layday
