### ISSUE TITLE
Some more addon managers

### ISSUE THREAD

**Issue by Nihlo** [ogri-la/wowman-comrades#29]
That's a very cool comparison for all those addon updaters out there. Thanks a lot.

Here are a few more you might want to add:

- https://curseforge.overwolf.com 
The official Curseforge Updater now

- https://www.minion.gg
The official WoWInterface Updater

- https://www.nexusmods.com/site/mods/1
A universal mod manager that also supports WoW

- https://github.com/AcidWeb/CurseBreaker
don't know anything about that^^

- https://www.wowmatrix.com
had trouble with mod authors about licenses years ago

Thanks again for your work.

**Comment by torkus** [comment]
Hi, thanks for opening a ticket.

Those addons are indeed on the list, there are just so many addon managers in different states that what I present to the public is constrained by a few default parameters.

If you look in the top left-hand corner you will see a dropdown with the label beside it *"some basic filtering, good for everybody"*.

If you change that to ["unfiltered"](https://ogri-la.github.io/wow-addon-managers/?preset/name=unfiltered&field/feature-wago.io=&field/feature-curseforge=&field/maintained=&field/software-licence=&field/windows=&field/eula=&field/feature-tukui=&field/ads=&field/source-available=&field/feature-wowinterface=&field/ui=&field/language=&field/feature-vcs-addons=&field/retail=&field/linux=&field/f-oss=&field/classic=&field/mac=&field/feature-catalog-search=) you will see all addon managers and all columns.

Please let me know if you ever come across an addon manager that isn't on the list. There haven't been any limitations as to what makes the list in the past but with Curse being acquired by Overwolf there was a splurge of new addon managers that didn't live for more than a few days or a few dozen commits and I've left these off to control some of the noise.
