### ISSUE TITLE
Singularity ends

### ISSUE THREAD

**Issue by Nomis9** [ogri-la/wowman-comrades#31]
> XORRO — 15.06.2021
Please forgive the soap box.
>
>One year ago, I watched the last good addon manager get sold off to a company with a terrible privacy track record and thought “screw it, I’ll have my own party.” My mission was to create an addon manager that I myself wanted to use. In September I released Singularity 0.1.0, ugly, orange, shallow in features, but technically functional and able to support all the WoW mods I personally used. From there I worked 20-40 hours a week on top of my normal job to continue adding features I personally wanted like multi-computer sync, remote backups, and additional addon sources. Somewhere down the trail, ESO players reached out and asked for the client to support their MMO of choice too.
>
>As Singularity’s active users ballooned from the 10s to the 10 of thousands, so did the costs. Singularity was a passion project of mine, so I justified it with “I’ve spent more money on dumber stuff” but that threshold was passed some time ago. The handful of gracious Patreon subscriptions cover around 5% - 10% of the monthly hosting expenses for Singularity’s infrastructure that has allowed it to survive the release of Shadowlands and multiple patch days without tipping over. It wasn’t always smooth sailing, but I did my best to keep the app working for as many people as possible.
>
>Unfortunately, yesterday’s requests by several addon authors to delist their mods has pushed Singularity to a tipping point. I would not personally want to use an addon manager that was missing multiple notable mods. Out of respect for their request, and in not wanting to deliver a subpar service, I’m pulling the plug.
>
>Effective June 19 I will begin archiving and decommissioning Singularity’s infrastructure. If you are a WoW player, WowUp is an excellent alternative. I plan on taking a break from addon manager development but will likely end up trying to help with pull requests to their client after some time. If you’re an ESO player, I’m sorry but its back to Minion for you.

**Comment by torkus** [comment]
cheers, @Nomis9 , singularity has been marked as unmaintained.
