### ISSUE TITLE
Rename "wago.io" feature to avoid confusion

### ISSUE THREAD

**Issue by layday** [ogri-la/wowman-comrades#32]
The "wago.io" feature refers to being able to update WAs installed from https://wago.io. When this feature was added https://addons.wago.io didn't exist.  As of [last week](https://github.com/WowUp/WowUp/releases/tag/v2.6.0-beta.12), WowUp supports https://addons.wago.io as a host.

**Comment by layday** [comment]
To use Wago in WowUp you have to consent to https://addons.wago.io/agreements/wowup-data-consent and ads will be displayed in the app.

**Comment by torkus** [comment]
hey @layday :)

yes, I was wondering if the nature of this feature had changed while doing updates today, thank you for opening the ticket.

I took a look at wowup and despite reading about the partnership that was reached with Wago I didn't see any change in the status of a ticket about adding support.

Does "WA" mean "Weak Aura" ? I think I might disable the column for now as it *is* confusing and the other two addon managers with this other kind of support are no longer maintained leaving just wowup. If other addon managers start shilling for wago I'll add the column back with it's new meaning as 'addon host'.

**Comment by torkus** [comment]
Deployed, the column has been removed.

Thanks again

**Comment by layday** [comment]
Makes sense, thanks. And yeah, WA is for weak aura.
