### ISSUE TITLE
WoWUp has CF support again

### ISSUE THREAD

**Issue by layday** [ogri-la/wowman-comrades#34]
https://www.wowhead.com/news/wowup-launches-new-addon-manager-supporting-curseforge-downloads-329736

**Comment by torkus** [comment]
I'm guessing it's a private fork of wowup with CF support. Seems like a lot of effort.

**edit**: my mistake, it's right here: https://github.com/WowUp/WowUp.CF/

**Comment by layday** [comment]
Yeah, the base edition has got Wago ads whereas this one has CF ads. Never the twain shall meet.

**Comment by layday** [comment]
Oh, and they are using a proprietary Electron build for the CF version, so it's not FOSS.

**Comment by torkus** [comment]
Serving ads is gross but maintaining a proprietary fork to maximise ad revenue while begging for donations and masking it all with:

> powered by the community

is really fucking gross.

**Comment by torkus** [comment]
> Oh, and they are using a proprietary Electron build for the CF version, so it's not FOSS.

That's an interesting point. The repo is GPL, but the releases when combined with a proprietary Electron are ...? Not clear at the very least. 

And am I referring to addon managers or addon manager *source code* in this repo? If source code, then I can list this as GPL and be done with it, if addon manager _apps_ then no ... hm.

**Comment by torkus** [comment]
I'm going to go with referring to the addon manager *app/release*, if it exists, for cases like this. If the source code can't be built without invalidating the project's licence, then the addon manager can't be used to manage addons under the terms of that licence so it would be misleading to advertise it as such.

**Comment by torkus** [comment]
done. Thanks for opening a ticket @layday

**Comment by layday** [comment]
Small correction, the CF version supports all of the same hosts, _except_ Wago Addons. 

> Serving ads is gross but maintaining a proprietary fork to maximise ad revenue while begging for donations and masking it all with:

As far as I know the ads are displayed in exchange for CF API access - WowUp doesn’t get a cut.

**Comment by torkus** [comment]
> Small correction, the CF version supports all of the same hosts, except Wago Addons.

fixed
