### ISSUE TITLE
vargen2/Addon not available since 27/9

### ISSUE THREAD

**Issue by layday** [ogri-la/wowman-comrades#6]
See the [readme](https://github.com/vargen2/Addon/blob/master/README.md).  Maybe this should be marked as unmaintained, I don't know.

**Comment by torkus** [comment]
I noticed this a little while ago. It's been a month now so I've opened a ticket

**Comment by torkus** [comment]
will take this off the 'maintained' list I think

**Comment by torkus** [comment]
removed from maintained list
