### ISSUE TITLE
WoWClassicUI

### ISSUE THREAD

**Issue by layday** [ogri-la/wowman-comrades#8]
Another closed alternative to CF and WoWI: https://github.com/wowclassicui/desktop

**Comment by torkus** [comment]
sorry I didn't get back to you earlier, I didn't see this one come in.

it looks similar to this one: https://github.com/WorldofAddons/worldofaddons

but I think that's just a JS thing

I'm going on holiday Monday and will have some free time to add it next week and look at some automation for all of this

**Comment by layday** [comment]
It communicates with their own website mirroring CF add-ons (which is bound to cause some grief) so not quite the same thing.

**Comment by torkus** [comment]
I found a similarly dodgy site out there the other day:

https://addonswow.com/

which appears to be using a wordpress site and registered to Russians.

wowclassicui looks like it's on a French/EU host: https://www.scaleway.com/

I'm guessing it's just ad revenue they're after like WoWMatrix

**Comment by torkus** [comment]
> mirroring CF add-ons (which is bound to cause some grief)

yes - all the `.zip` files here are addons: https://classicwarcraft.s3.fr-par.scw.cloud/

not cool

**Comment by layday** [comment]
> I'm guessing it's just ad revenue they're after like WoWMatrix

It doesn't look like they're serving any ads.  I don't know what their end goal actually is but they'd have managed to alienate all add-on authors in one fell swoop.

**Comment by torkus** [comment]
Huge maintenance burden as well. The audacity of these guys... I was toying with the idea of a purely static html and json 'API' hosted on github but I think it would be too easy to broadcast the wrong impression to the world - like these guys are doing.

**Comment by layday** [comment]
That's also one of the reasons I was reluctant to add a search command to *instawow* originally - users would be forced to interact with the add-on host.

**Comment by torkus** [comment]
added

**Comment by layday** [comment]
'retail' should be 'no', I'd make a PR but I think it's easier for you to fix.

**Comment by torkus** [comment]
I guess so, it's right there in the name ;)

**Comment by torkus** [comment]
all done.

I've just merged some other changes that help me automate things. The 'master' copy of the `comrades.csv` file is now `comrades.raw.csv` whose data updated from github and written out to `comrades.csv` and the `noscript` part of the website. It lets me ensure certain values are not overwritten
